version: '3'
services:
  mosquitto:
    image: ruimarinho/mosquitto
    container_name: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    networks: 
      # - regional_gateway-network
      - mqtt-network
    volumes:
      - ./templates/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

## MiNiFi

  minifi:
    image: apache/nifi-minifi:0.5.0
    container_name: minifi-gateway
    ports:
      - 8081:8080
    volumes:
      - ./templates/minifi/container/config.yml:/opt/minifi/minifi-0.5.0/config.yml
      - ./templates/minifi/NAR/:/opt/minifi/minifi-0.5.0/etc/
    networks: 
      - mqtt-network
      - regional_gateway-network
    entrypoint: /bin/sh
    command: -c "cp /opt/minifi/minifi-0.5.0/etc/* /opt/minifi/minifi-0.5.0/lib/ && ls /opt/minifi/minifi-0.5.0/lib/ && chmod +x /opt/minifi/minifi-0.5.0/bin/minifi.sh && /opt/minifi/minifi-0.5.0/bin/minifi.sh run"
    # command: -c "ls /opt/minifi/minifi-0.5.0/etc/"
    # command: -c "wget"
      # - gatweay_default

  minifi-toolkit:
    image: itarano/minifi-toolkit:0.5.0
    container_name: minifi-toolkit
    entrypoint: /bin/sh
    command: -c "./config.sh transform /opt/minifi/template-teste.xml /opt/minifi/config.yml"
    volumes:
      - ./templates/minifi/container/:/opt/minifi/
     
volumes:
  mongodb-data:
  minio-data:
  minio-config:
  rabbitmq-data:
  ui-data:
  # nifi-data-gateway:

  
networks: 
  mqtt-network:
    driver: bridge
  regional_gateway-network:
    external: true
  