version: '3'
services:

  mosquitto:
    image: amd64/eclipse-mosquitto
    container_name: mosquitto
    restart: always
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    networks: 
      - network
    volumes:
      - ./templates/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

## Python
  python:
    build: ./builds/python/
    container_name: python
    restart: always
    depends_on: 
      - mosquitto
    stdin_open: true
    tty: true
    networks: 
      - regional_network
      - network
  
networks: 
  network:
    driver: bridge
  regional_network:
    external: true
  