version: '3'
services:

  mosquitto:
    image: ruimarinho/mosquitto
    container_name: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    networks: 
      # - regional_gateway-network
      - mqtt-network
    volumes:
      - ./templates/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

## Python
  python:
    build: ./builds/python/
    container_name: python-processor
    depends_on: 
      - mosquitto
    stdin_open: true
    tty: true
    # command: -c "tail -f /dev/null"
    networks: 
      - regional_gateway-network
      - mqtt-network
    # volumes:
    #   - ./python_data/:./


     
volumes:
  mongodb-data:
  minio-data:
  minio-config:
  rabbitmq-data:
  ui-data:
  nifi-data-gateway:

  
networks: 
  mqtt-network:
    driver: bridge
  regional_gateway-network:
    external: true
  